name: mmt_club
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  expandable_bottom_bar: ^2.0.2
  flutter_neumorphic: ^3.0.3
  google_fonts: ^3.0.1
  #flutter_swiper: ^1.1.6
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^0.21.0
  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.15
  #contactus: ^1.2.0
  sleek_circular_slider: ^2.0.1
  adaptive_action_sheet: ^2.0.1
  font_awesome_flutter: ^9.2.0

  flutter_login: ^3.0.0
  sms_otp_auto_verify: ^2.1.0

  qr_code_scanner: ^0.6.0
  
  path_provider:
  get_it: ^7.2.0

  firebase_messaging: ^11.2.12
  firebase_core: ^1.14.0
  
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  url_launcher: ^6.1.5
  shimmer: ^2.0.0
  filter_list: ^1.0.2
  animated_text_kit: ^4.1.0
  rflutter_alert: ^2.0.4
  connectivity_plus: ^2.3.6+1
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_lints: ^1.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/iconApp.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: assets/images/iconApp.png

flutter:

 
  uses-material-design: true

  assets:
    - lib/Langs/ar.json
    - lib/Langs/en.json
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-Bold.ttf

    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-Light.otf
          weight: 300
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 700


