// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwyc6iF2qQ6wtmLQ1Mam8dnY-zwn-H2o4',
    appId: '1:32604681038:web:79822e3863f029d8ede41f',
    messagingSenderId: '32604681038',
    projectId: 'mmt-club',
    authDomain: 'mmt-club.firebaseapp.com',
    storageBucket: 'mmt-club.appspot.com',
    measurementId: 'G-Y5ZPRMV9HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpVOHJ1mD2KUnR6Tk2v9RpnP8NN8XjoR8',
    appId: '1:32604681038:android:bcc138ac9d929ef7ede41f',
    messagingSenderId: '32604681038',
    projectId: 'mmt-club',
    storageBucket: 'mmt-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIzIwrb7N07o0_FdArkGU9-QGJ23-IIx0',
    appId: '1:32604681038:ios:1e1979c1b33c42abede41f',
    messagingSenderId: '32604681038',
    projectId: 'mmt-club',
    storageBucket: 'mmt-club.appspot.com',
    iosClientId: '32604681038-5inuau7qcka6g5l0nid069i03fu46as9.apps.googleusercontent.com',
    iosBundleId: 'com.souccar.mmtclub',
  );
}
